version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: wii
    main: ./cmd/wii
    binary: wii
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X wii/internal/config.Version={{.Version}}
      - -X wii/internal/config.Commit={{.ShortCommit}}
      - -X wii/internal/config.Date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

upx:
  - ids: [wii]
    enabled: true
    goos: ["windows", "linux"]
    goarch: ["amd64","386"]
    compress: best

archives:
  - format: binary
    allow_different_binary_count: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^*.md"
      - "^*.ya?ml"

release:
  github:
    owner: oopsunix
    name: wii
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
